# Generated by Django 5.2.1 on 2025-05-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNew',
            fields=[
                ('category_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_number', models.IntegerField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorynew')),
            ],
        ),
    ]
