# Generated by Django 5.2.1 on 2025-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_barcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
