# Generated by Django 5.2.1 on 2025-05-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryNew',
            new_name='Category',
        ),
    ]
