# Generated by Django 5.2.1 on 2025-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='Customer', max_length=40)),
                ('customer_address', models.CharField(default='Baseco', max_length=100)),
                ('customer_number', models.IntegerField(max_length=11, null=True)),
            ],
        ),
    ]
