# Generated by Django 5.2.1 on 2025-05-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_items_order_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_barcode',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
