# Generated by Django 5.2.1 on 2025-05-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_categorynew_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
