# Generated by Django 5.2.1 on 2025-06-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_barcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
