# Generated by Django 5.2.1 on 2025-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
