# Generated by Django 5.2.1 on 2025-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customer_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(default='NO Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='No Customer Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
