# Generated by Django 5.2.1 on 2025-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customer_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
