GET http://127.0.0.1:8000/product/?page=2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNDQzMDAyLCJpYXQiOjE3NTE0MjUwMDIsImp0aSI6ImZiZDZhMjlmMWM3MjRmZDI5MGMzNDZmYzJkZWQyMGZjIiwidXNlcl9pZCI6Mn0.lFTnVAtMPt4aWf38whWDmScqow1yeGZZHuCDgDOr5mQ
content-type: application/json

###
GET http://127.0.0.1:8000/transaction/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxODI2Nzc5LCJpYXQiOjE3NTE4MDg3NzksImp0aSI6Ijg1OGM5NDgxOTdhYTRmNWVhMzgyMmU4MmNiM2Q3OTc5IiwidXNlcl9pZCI6Mn0.7DR4PtCdSyqE2M1OuUrb8-KlXOlF5-M0pV-OBwWBaZ8
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "email": "perberto07@gmail.com",
  "password": "perberto07"
}
###
### Request to protected endpoint
GET http://127.0.0.1:8000/protected/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNDQzMDAyLCJpYXQiOjE3NTE0MjUwMDIsImp0aSI6ImZiZDZhMjlmMWM3MjRmZDI5MGMzNDZmYzJkZWQyMGZjIiwidXNlcl9pZCI6Mn0.lFTnVAtMPt4aWf38whWDmScqow1yeGZZHuCDgDOr5mQ
