GET http://127.0.0.1:8000/product/1 HTTP/1.1
content-type: application/json

###
PUT http://127.0.0.1:8000/transaction/ HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "email": "perberto08@gmail.com",
  "password": "perberto07"
}
###
### Request to protected endpoint
GET http://127.0.0.1:8000/protected/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMjE3NDQ3LCJpYXQiOjE3NTExOTk0NDcsImp0aSI6IjlhMTkyNTM1ZjAxYjQ2MDA5N2IxOGMwOTU4OWU0NTNhIiwidXNlcl9pZCI6Mn0.D83TxxqbDv5uOJRgLunbv5OVAB_HSA2LWsB1wc1ofnk

