POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "email": "patrick@gmail.com",
  "password": "lala14"
}
###
GET http://127.0.0.1:8000/users/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxODY5ODgzLCJpYXQiOjE3NTE4NTE4ODMsImp0aSI6Ijc0YTIwMTMwODFmODRiMzNhYzc2MDZlNTYxNjZkY2ExIiwidXNlcl9pZCI6Mn0.ZyuX-sHgpN-V0w02y7ABT3mkyEtMHX4QdXgKY7lZWOI
Content-Type: : application/json